README.md, deploy.sh
=> deploy script has been implemented

frontend/src/metabase/visualizations/lib/settings/dashcard_locales.js
1. Book distribution related localized title added.
=> Book distribution related localized title added.

frontend/src/metabase/visualizations/lib/settings/dashcard_locales.js
- book distribution preview title added.
=> Book distribution admin dashboard preview title added.

frontend/src/metabase/visualizations/lib/settings/dashcard_locales.js
1. Fixed existing title spelling.
2. Added new title.
=> Question title add fix

frontend/src/metabase/visualizations/lib/settings/dashcard_locales.js
1. Unwanted space removed.
2. Actually i wanted to test the staging branch push doing the image push in dsinnovators.
=> Unwanted space removed.

.github/workflows/build-release-push.yml, bin/build-mb/src/build.clj, deploy.sh, version.json
=> GitHub action testing

frontend/src/metabase/visualizations/lib/settings/dashcard_locales.js, version.json
=> message update

frontend/src/metabase/visualizations/lib/settings/dashcard_locales.js, version.json
=> dashboard message for school and tangerine

frontend/src/metabase/visualizations/lib/settings/dashcard_locales.js, version.json
=> Key modified.

frontend/src/metabase/visualizations/lib/settings/dashcard_locales.js, version.json
=> message property added for case managemnet dashboard questions

frontend/src/metabase/visualizations/lib/settings/dashcard_locales.js, version.json
=> Teacher age group statistics dashboard card title updated.

frontend/src/metabase/visualizations/lib/settings/dashcard_locales.js
=> New dashboard titles are added.

version.json
=> Version updated.

frontend/src/metabase/visualizations/lib/settings/dashcard_locales.js, version.json
=> Few minor label fixation.

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, frontend/src/metabase/lib/click-behavior.js, version.json
=> Pass dashboard param to click behavior

frontend/src/metabase/lib/click-behavior.js, version.json
=> Instance of check updated.

frontend/src/metabase/visualizations/lib/settings/dashcard_locales.js, version.json
[IEIMS-4909](https://dsi-dpe.atlassian.net/browse/IEIMS-4909)
=> IEIMS-4909

frontend/src/metabase/visualizations/lib/settings/dashcard_locales.js, version.json
- dashboard_locales.js file updated
=> dashboard_locales.js file updated

frontend/src/metabase/visualizations/lib/settings/dashcard_locales.js, version.json
=> Version_39

frontend/src/metabase/lib/formatting/link.js, version.json
- In the click behavior null values are treated as no value present.
=> Treating null as value missing for click behavior

frontend/src/metabase/css/core/link.css, frontend/src/metabase/visualizations/components/Table.css, version.json
=> table data line height fix

frontend/src/metabase/visualizations/lib/settings/dashcard_locales.js, version.json
[bug link](https://dsi-dpe.atlassian.net/browse/IEIMS-6082)
=> card title bug fix

frontend/src/metabase/visualizations/lib/settings/dashcard_locales.js, version.json
=> ppe : renamed monitoring related info
